language: objective-c
osx_image: xcode7
xcode_workspace: fh-ios-sdk.xcworkspace
xcode_scheme: FH
xcode_sdk: iphonesimulator

before_install:
    - gem install cocoapods -v '0.39.0' obcd slather -N --no-rdoc --no-ri --no-document --quiet

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master
after_success: slather